version: '3'
services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - ./:/var/www/html
        networks:
            - backend

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql
        networks:
            - backend

    mysql:
        image: mysql:5.7.28
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: trouble
            MYSQL_USER: trouble
            MYSQL_PASSWORD: trouble
            MYSQL_ROOT_PASSWORD: trouble
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - backend

    npm:
        image: node:alpine
        container_name: npm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        #entrypoint: ["npm"]

networks:
    backend:
        driver: bridge
